url: https://blog.toolstud.io
name: Toolstud.io Blog
title: Toolstud.io Blog
description: web-based tools, converters and calculators

baseurl: "/"
twitter_username: pforret
github_username:  pforret

highlighter:      rouge
permalink:        pretty

paginate:         10

author:
  name:   'Peter Forret'
  url:    https://twitter.com/pforret

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - hyde
  - .idea/