url: https://blog.toolstud.io
name: Toolstud.io Blog
title: Toolstud.io Blog
description: tools, converters and calculators

baseurl: ""
twitter_username: pforret
github_username:  pforret

highlighter:      rouge
permalink:        pretty

paginate:         10

author:
  name:   'Peter Forret'
  url:    https://toolstud.io

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - hyde
  - .idea/